version: "3.8"
services:
  db:
    container_name: postgres_container
    image: postgres
    hostname: picpay
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: picpay_db
    ports:
      - "5432:5432"
    networks:
      network:
        ipv4_address: 10.5.0.4
  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      network:
        ipv4_address: 10.5.0.5
volumes:
  db:
    driver: local
networks:
  network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1